- job:
    name: github-pipeline
    project-type: pipeline
    defaults: global
    pipeline-scm:
      script-path: "Jenkinsfile"
      scm:
        - git:
            url: "https://github.com/NishanWijesinghe/devops-aws-demo.git"
            clean: true

    triggers:
      - pollscm:
          cron: "*/2 * * * *"
